name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup SBCL
      uses: cheeze2000/setup-sbcl@main
      with:
        version: 2.4.2

    - name: Setup Qob
      uses: cl-qob/setup-qob@master
      with:
        version: 'snapshot'

    - name: Run tests
      run: |
        qob install-deps --dev
        qob test
